### ISSUE TITLE
Argument #1 ($language) must be of type ?string

### ISSUE THREAD

**Issue by itrack** [weareantenna/inline-translations#8]
TypeError: Antenna\InlineTranslations\Controllers\ApiController::fetch(): Argument #1 ($language) must be of type ?string, Antenna\InlineTranslations\TranslationFetcher given, called in /Users/alex/Projects/PHP/couriermanager/vendor/laravel/framework/src/Illuminate/Routing/Controller.php on line 54 in file /Users/alex/Projects/PHP/couriermanager/vendor/antenna/inline-translations/src/Controllers/ApiController.php on line 0

**Comment by itrack** [comment]
the problem is from here:
src/Controllers/ApiController.php:19

Current code:
public function fetch(?string $language = null, TranslationFetcher $fetcher): JsonResponse

Fix:
public function fetch(TranslationFetcher $fetcher, ?string $language = null): JsonResponse

**Comment by kristoffeys** [comment]
this was fixed here: https://github.com/weareantenna/inline-translations/commit/289bd61bd8d28854b45fe75bfde1365ee0b9403c
